# Generated by Django 2.2.28 on 2023-03-14 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budhub', '0004_auto_20230314_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='source',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='source',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='catalog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_catalog', to='budhub.Product_catalog'),
        ),
    ]
