# Generated by Django 2.2.28 on 2023-03-14 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budhub', '0005_auto_20230314_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_source', to='budhub.Inventory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_source', to='budhub.Assets'),
        ),
    ]
