# Generated by Django 2.2.28 on 2023-03-14 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budhub', '0006_auto_20230314_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=256)),
                ('abbreviation', models.CharField(max_length=10)),
                ('qty_unit', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_unit', to='budhub.Units'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_unit', to='budhub.Units'),
        ),
    ]
