# Generated by Django 2.2.28 on 2023-03-14 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budhub', '0007_auto_20230314_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_items_order', to='budhub.Orders')),
            ],
        ),
    ]
