# Generated by Django 2.2.28 on 2023-03-14 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budhub', '0008_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_order', to='budhub.Orders'),
        ),
        migrations.AddField(
            model_name='assets',
            name='package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_package', to='budhub.Line_items'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_order', to='budhub.Orders'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_package', to='budhub.Line_items'),
        ),
    ]
