# Generated by Django 2.2.28 on 2023-03-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230309_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invoice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
