# Generated by Django 2.2.28 on 2023-03-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230314_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
